[package]
name = "aoc_util"
version = "0.1.0"
authors = ["Maxwell French <maxwell@frenchnet.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
